# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: cms_dev
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:8.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: cms_dev
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --username root --password root --authenticationDatabase admin --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # MySQL
      DB_TYPE: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: cms_dev
      TEST_DB_NAME: cms_test
      # MongoDB
      MONGO_URL: 'mongodb://root:root@127.0.0.1:27017/cms_dev?authSource=admin'
      # Redis (not used in CI)
      REDIS_URL: 'redis://localhost:6379'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24.x & cache modules
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # wait until both MySQL & Mongo are healthy
      - name: Wait for MySQL & Mongo
        run: |
          for i in {1..12}; do
            mysqladmin ping --host=127.0.0.1 --silent && \
            mongosh --username root --password root --authenticationDatabase admin --quiet --eval 'db.adminCommand({ping:1})' \
              && echo "All databases healthy" && break
            echo "Waiting for databases ($i/12)…"
            sleep 5
          done

      - name: Setup Databases (migrations + seed)
        run: npm run db:setup

      - name: Lint code
        run: npm run lint

      - name: Format code
        run: npm run format

      - name: Run tests
        run: npm test
