# C:\Users\Pubg\Documents\cms-project\.github\workflows\ci.yml
# Description: GitHub Actions workflow for CI, running lint, format, and test on push/pull_request
# Created: July 22, 2025, 10:35 AM IST
# Updated: July 22, 2025, 10:35 AM IST
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '24' }
      - run: npm install
      - run: npm run lint
      - run: npm run format
      - run: npm test
